//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikbulatovLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BikbulatovLibraryEntities : DbContext
    {

        private static BikbulatovLibraryEntities _context;

        public static BikbulatovLibraryEntities GetContext()
        {
            if (_context == null)
                _context = new BikbulatovLibraryEntities();
            return _context;
        }
        public BikbulatovLibraryEntities()
            : base("name=BikbulatovLibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<FundReplenishment> FundReplenishment { get; set; }
        public virtual DbSet<Library> Library { get; set; }
        public virtual DbSet<LibraryFund> LibraryFund { get; set; }
        public virtual DbSet<LiteratureType> LiteratureType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
