//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BikbulatovLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryFund
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LibraryFund()
        {
            this.FundReplenishment = new HashSet<FundReplenishment>();
        }
    
        public int FundID { get; set; }
        public string FundName { get; set; }
        public int LibraryID { get; set; }
        public int Books { get; set; }
        public int Magazines { get; set; }
        public int Newspapers { get; set; }
        public int Collections { get; set; }
        public int Dissertations { get; set; }
        public int Abstracts { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FundReplenishment> FundReplenishment { get; set; }
        public virtual Library Library { get; set; }
    }
}
